package de.shopme.testing.system.tools.knowledge.catalog.review.classification

enum class CatalogReviewBacklogClassification {

    SEMANTIC_CATEGORY_CONFLICT,

    SINGULAR_PLURAL_VARIANT,
    TYPO_VARIANT,
    PUNCTUATION_VARIANT,
    WORD_ORDER_VARIANT,
    SALES_FORM_VARIANT,
    PREPARATION_VARIANT,
    BRAND_VARIANT,
    POSSIBLE_SEMANTIC_DUPLICATE,

    MULTIPLE_DUPLICATE_REASONS,

    SPLIT_REQUIRED,

    UNCLASSIFIED_REVIEW,

    FROZEN_FORM_VARIANT,

    CANNED_FORM_VARIANT,

    BIO_ATTRIBUTE_VARIANT,
}