package de.shopme.testing.system.tools.knowledge.catalog.duplicate

enum class CatalogDuplicateReason {
    IDENTICAL_ITEM_NAME,
    IDENTICAL_NORMALIZED_KEY,
    NORMALIZED_NAME_MATCH,
    SINGULAR_PLURAL_VARIANT,
    WORD_ORDER_VARIANT,
    PUNCTUATION_VARIANT,
    COLOR_ORDER_VARIANT,
    PREPARATION_VARIANT,
    SALES_FORM_VARIANT,
    BRAND_VARIANT,
    TYPO_VARIANT,
    POSSIBLE_SEMANTIC_DUPLICATE
}