package de.shopme.testing.system.tools.knowledge.catalog.duplicate.resolution.diagnostics

enum class CatalogTypoCandidateDiagnosticReason {

    SOURCE_ENTRY_NOT_FOUND,
    TARGET_ENTRY_NOT_FOUND,

    MISSING_MERGE_TARGET,
    SELF_REFERENCING_MERGE_TARGET,

    UNSUPPORTED_PLAN_ACTION,
    MISSING_TYPO_REASON,
    CONFLICTING_DUPLICATE_REASON,
    UNKNOWN_PLAN_REASON,

    CATEGORY_MISMATCH,

    EMPTY_SOURCE_NAME,
    EMPTY_TARGET_NAME,
    IDENTICAL_COMPARISON_TEXT,

    NUMERIC_TOKEN_MISMATCH,
    TOKEN_COUNT_MISMATCH,

    NO_DIFFERING_TOKEN,
    MULTIPLE_DIFFERING_TOKENS,

    TOKEN_BELOW_MINIMUM_LENGTH,

    GERMAN_ORTHOGRAPHY_EQUIVALENT,
    COMPOUND_SPACING_EQUIVALENT,
    HYPHENATION_EQUIVALENT,
    TYP_TYPE_EQUIVALENT,
    SAUCE_SOSSE_EQUIVALENT,

    EDIT_DISTANCE_ONE,
    EDIT_DISTANCE_EXCEEDS_LIMIT,
    LENGTH_DIFFERENCE_EXCEEDS_LIMIT,

    EXISTING_RESOLVER_SHOULD_HAVE_ACCEPTED,
    MANUAL_SEMANTIC_REVIEW_REQUIRED
}