package de.shopme.testing.system.tools.knowledge.catalog.expansion.semantic

enum class CanonicalExpansionSemanticRuleType {
    FAMILY_AXIS_COMPATIBILITY,
    FAMILY_VALUE_COMPATIBILITY,
    MUTUALLY_EXCLUSIVE_VALUES,
    REDUNDANT_FAMILY_VALUE,
    REDUNDANT_AXIS_PAIR,
    IMPOSSIBLE_DIETARY_FORM,
    IMPOSSIBLE_PROCESSING_STATE,
    IMPOSSIBLE_PRESERVATION_STATE,
    IMPOSSIBLE_ANIMAL_PLANT_COMBINATION,
    FAMILY_SPECIFIC_ACCEPTANCE,
    FAMILY_SPECIFIC_REVIEW
}