package de.shopme.testing.system.tools.knowledge.catalog.expansion.refinement

enum class CanonicalTargetDistributionIssueType {
    INVALID_BASELINE_REFERENCE,
    GLOBAL_TARGET_MISMATCH,
    UNKNOWN_CATEGORY,
    MISSING_CATEGORY,
    TARGET_BELOW_BASELINE,
    CATEGORY_TARGET_SUM_MISMATCH,
    EMPTY_IDENTITY_SCOPE,
    SKU_AXIS_ALLOWED_AS_IDENTITY,
    REQUIRED_SKU_AXIS_NOT_EXCLUDED,
    UNJUSTIFIED_CATEGORY_TARGET,
    EXCESSIVE_SINGLE_CATEGORY_SHARE
}