package de.shopme.tools.knowledge.catalog.canonical.completeness

data class RequiredCanonicalFoodIdentity(
    val itemname: String,
    val normalized: String,
    val category: String
)

object GermanSupermarketCanonicalIdentityRegistry {

    val identities =
        listOf(
            RequiredCanonicalFoodIdentity(
                "Äpfel",
                "aepfel",
                "fruit"
            ),
            RequiredCanonicalFoodIdentity(
                "Bananen",
                "bananen",
                "fruit"
            ),
            RequiredCanonicalFoodIdentity(
                "Erdbeeren",
                "erdbeeren",
                "fruit"
            ),
            RequiredCanonicalFoodIdentity(
                "Beerenmischung",
                "beerenmischung",
                "fruit"
            ),
            RequiredCanonicalFoodIdentity(
                "Tomaten",
                "tomaten",
                "vegetables"
            ),
            RequiredCanonicalFoodIdentity(
                "Cocktailtomaten",
                "cocktailtomaten",
                "vegetables"
            ),
            RequiredCanonicalFoodIdentity(
                "Kartoffeln",
                "kartoffeln",
                "vegetables"
            ),
            RequiredCanonicalFoodIdentity(
                "Karotten",
                "karotten",
                "vegetables"
            ),
            RequiredCanonicalFoodIdentity(
                "Vollmilch",
                "vollmilch",
                "dairy"
            ),
            RequiredCanonicalFoodIdentity(
                "Naturjoghurt",
                "naturjoghurt",
                "dairy"
            ),
            RequiredCanonicalFoodIdentity(
                "Butter",
                "butter",
                "dairy"
            ),
            RequiredCanonicalFoodIdentity(
                "Rindfleisch",
                "rindfleisch",
                "meat"
            ),
            RequiredCanonicalFoodIdentity(
                "Schweinefleisch",
                "schweinefleisch",
                "meat"
            ),
            RequiredCanonicalFoodIdentity(
                "Hähnchenfleisch",
                "haehnchenfleisch",
                "meat"
            ),
            RequiredCanonicalFoodIdentity(
                "Lachs",
                "lachs",
                "fish"
            ),
            RequiredCanonicalFoodIdentity(
                "Forelle",
                "forelle",
                "fish"
            ),
            RequiredCanonicalFoodIdentity(
                "Apfelsaft",
                "apfelsaft",
                "beverages"
            ),
            RequiredCanonicalFoodIdentity(
                "Orangensaft",
                "orangensaft",
                "beverages"
            ),
            RequiredCanonicalFoodIdentity(
                "Cola",
                "cola",
                "beverages"
            ),
            RequiredCanonicalFoodIdentity(
                "Mineralwasser",
                "mineralwasser",
                "beverages"
            ),
            RequiredCanonicalFoodIdentity(
                "Roggenbrot",
                "roggenbrot",
                "bakery"
            ),
            RequiredCanonicalFoodIdentity(
                "Vollkornbrot",
                "vollkornbrot",
                "bakery"
            ),
            RequiredCanonicalFoodIdentity(
                "Weizenbrötchen",
                "weizenbroetchen",
                "bakery"
            )
        )
}