package de.shopme.testing.system.tools.knowledge.catalog.category


enum class CatalogCategoryIssueType {
    MISSING_CATEGORY,
    EMPTY_CATEGORY,
    UNKNOWN_CATEGORY,
    NON_NORMALIZED_CATEGORY_KEY,
    CATEGORY_DISPLAY_NAME_USED_AS_KEY,
    CATEGORY_KEY_CASE_MISMATCH,
    CATEGORY_KEY_WHITESPACE,
    CATEGORY_KEY_UNDERSCORE,
    CATEGORY_KEY_INVALID_CHARACTERS,
    AMBIGUOUS_CATEGORY_REFERENCE,
    ROOT_CATEGORY_ASSIGNED_TO_ITEM,
    CATEGORY_WITHOUT_CATALOG_ITEMS,
    CATEGORY_WITH_VERY_FEW_ITEMS,
    CATEGORY_WITH_UNUSUALLY_MANY_ITEMS,
    POSSIBLE_CATEGORY_ALIAS,
    POSSIBLE_MISCLASSIFICATION
}