package de.shopme.testing.system.tools.knowledge.catalog.review.analysis

enum class CatalogReviewResolutionRecommendation {
    IMPLEMENT_SINGULAR_PLURAL_RESOLVER,
    IMPLEMENT_TYPO_VARIANT_RESOLVER,
    IMPLEMENT_PUNCTUATION_VARIANT_RESOLVER,
    IMPLEMENT_WORD_ORDER_VARIANT_RESOLVER,
    IMPLEMENT_SALES_FORM_VARIANT_CLASSIFIER,
    IMPLEMENT_PREPARATION_VARIANT_CLASSIFIER,
    IMPLEMENT_BRAND_VARIANT_POLICY,
    REVIEW_POSSIBLE_SEMANTIC_DUPLICATES,
    REVIEW_SEMANTIC_CATEGORY_CONFLICTS,
    RESOLVE_SPLIT_ACTIONS,
    REVIEW_UNCLASSIFIED_ENTRIES,
    REVIEW_CONFLICTING_EVIDENCE,
    PRESERVE_DISTINCT_PRODUCT_FORMS,
}